namespace UnityEngine.XR.AREngine
{
    public enum HwArHealthParameterType
    {
        HWAR_PARAMETER_INVILID = 0,
        HWAR_PARAMETER_HEART_RATE = 1,
        HWAR_PARAMETER_HEART_RATE_SNR = 2,
        HWAR_PARAMETER_HEART_RATE_CONFIDENCE = 3,
        HWAR_PARAMETER_BREATH_RATE = 4,
        HWAR_PARAMETER_BREATH_RATE_SNR = 5,
        HWAR_PARAMETER_BREATH_RATE_CONFIDENCE = 6,
        HWAR_PARAMETER_FACE_AGE = 7,
        HWAR_PARAMETER_GENDER_MALE_WEIGHT = 8,
        HWAR_PARAMETER_GENDER_FEMALE_WEIGHT = 9,
        HEAR_PARAMETER_FACE_HEALTH_STATUS = 13,
        HEAR_PARAMETER_FACE_HEALTH_PROC_PROGRESS = 14,
        HEAR_PARAMETER_HEART_WAVE = 15,
        HEAR_PARAMETER_SPO2_VALUE = 16,
    }
}