namespace UnityEngine.XR.AREngine
{
    public enum HwArCloudAnchorState
    {
        HWAR_CLOUD_ANCHOR_STATE_NONE = 0,
        HWAR_CLOUD_ANCHOR_STATE_TASK_IN_PROGRESS = 1,
        HWAR_CLOUD_ANCHOR_STATE_SUCCESS = 2,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_INTERNAL = -1,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_NOT_AUTHORIZED = -2,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_SERVICE_UNAVAILABLE = -3,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_RESOURCE_EXHAUSTED = -4,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_HOSTING_DATASET_PROCESSING_FAILED = -5,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_CLOUD_ID_NOT_FOUND = -6,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_RESOLVING_LOCALIZATION_NO_MATCH = -7,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_RESOLVING_SDK_VERSION_TOO_OLD = -8,
        HWAR_CLOUD_ANCHOR_STATE_ERROR_RESOLVING_SDK_VERSION_TOO_NEW = -9,
    }
}